# Docker compose for testing
version: "2"
services:
  test:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: npm test
    environment:
      - NODE_ENV=test
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=qwerty
    links:
      - db
    volumes:
      - .:/app
      - /app/node_modules
  db:
    image: jofan/couchdb-tester:latest
    ports:
      - '5994:5984'
